function [CIETHeaterStates,HeaterState1] = CIETHeaterStates(NumericControls,CIETData)
CIETHeaterStates(1) = NumericControls.DesiredPower;
CIETHeaterStates(2) = CIETData.CX101;
CIETHeaterStates(3) = CIETData.CX102;
CIETHeaterStates(4) = CIETData.CX103;
CIETHeaterStates(5) = CIETData.CX104;
CIETHeaterStates(6) = CIETData.CX111;
CIETHeaterStates(7) = CIETData.CX112;
CIETHeaterStates(8) = CIETData.CX113;
CIETHeaterStates(9) = CIETData.CX114;
CIETHeaterStates(10) = CIETData.WT10;
CIETHeaterStates(11) = CIETData.BT11;
CIETHeaterStates(12) = CIETData.ST14E;
CIETHeaterStates(13) = CIETData.ST14W;
CIETHeaterStates(14) = CIETData.ST14N;
CIETHeaterStates(15) = CIETData.FM40;
HeaterState1.TFH = mean(CIETHeaterStates(2:9));
HeaterState1.TSH = mean(CIETHeaterStates(12:14));