:: --------------------------------------------------------
:: This file was generated by NI VeriStand Model Framework
:: Version : 2018.0.0.81 (2018)
:: Generated on : 14-Mar-2019 16:45:38
:: --------------------------------------------------------

set MATLAB=C:\Program Files\MATLAB\R2017a
set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\
call "C:\VeriStand\2018\ModelInterface\tmw\toolchain\nivs_vcvars32_100.bat"
@if errorlevel 1 goto error_exit


:make
cd /d %~dp0
nmake -f NACCBraytonCycle2017a.mk  ISPROTECTINGMODEL=NOTPROTECTING EXT_MODE=0 EXTMODE_STATIC_ALLOC=0 TMW_EXTMODE_TESTING=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 MAT_FILE=1 NIDEBUG=0 NIOPT="Default" OPTS="" /I

 
@if errorlevel 1 goto error_exit
exit /B 0

:error_exit
echo The make command returned an error of %errorlevel%
An_error_occurred_during_the_call_to_make
